### ISSUE TITLE
Manuel Zoom

### ISSUE THREAD

**Issue by ersofis** [irmgrx/igar#1]
Manual Zoom please :) 
I'm the director of Agarclan the page.

**Comment by irmgrx** [comment]
What's that mean?
This tool haven't tested on other browsers except firefox.
However, the zoom function should work fine.
You can either zoom by mouse wheel or pressing key "1" - "4" on the keyboard.

**Comment by ersofis** [comment]
My English is not good.

See Auto and manual zoom zoom in Agarplus v2 and v1 version . You will understand this.

**Comment by ersofis** [comment]
Do not zoom out automatically .

**Comment by ersofis** [comment]
https://youtu.be/zZV_H_Od5lI

**Comment by irmgrx** [comment]
Thanks for your advice!
I will take a look later.

**Comment by irmgrx** [comment]
The function has been added.

**Comment by ersofis** [comment]
Thank you.
